FROM nginx:mainline-alpine

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*
ADD nginx.conf /etc/nginx/nginx.conf
ADD fargate_site.conf /etc/nginx/sites-enabled/site.conf
ADD htpasswd /etc/nginx/.htpasswd
EXPOSE 80
