# Generated by Django 2.2.13 on 2020-07-25 02:49

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(db_index=True, default=django.utils.timezone.now, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='category/image/%Y%m%d', verbose_name='カテゴリイメージ'),
            preserve_default=False,
        ),
    ]
